// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Owin")]
[assembly: AssemblyDescriptionAttribute("Camada principal da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Owin")]
[assembly: GuidAttribute("968cf1d6-3467-4103-93b7-557fe281f0b9")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Owin";
        internal const System.String AssemblyDescription = "Camada principal da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Owin";
        internal const System.String Guid = "968cf1d6-3467-4103-93b7-557fe281f0b9";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
