// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Binding")]
[assembly: AssemblyDescriptionAttribute("Camada de configuração de registros para inversão de controle e injeção de dependência da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Binding")]
[assembly: GuidAttribute("5cd2e917-56f0-4e62-9a59-3e74ba9a1fde")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Binding";
        internal const System.String AssemblyDescription = "Camada de configuração de registros para inversão de controle e injeção de dependência da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Binding";
        internal const System.String Guid = "5cd2e917-56f0-4e62-9a59-3e74ba9a1fde";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
