// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Common.Abstraction")]
[assembly: AssemblyDescriptionAttribute("Camada de abstrações compartilhadas da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Common.Abstraction")]
[assembly: GuidAttribute("0ef0726e-3e34-4362-84f6-ba1a8fcf8d14")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Common.Abstraction";
        internal const System.String AssemblyDescription = "Camada de abstrações compartilhadas da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Common.Abstraction";
        internal const System.String Guid = "0ef0726e-3e34-4362-84f6-ba1a8fcf8d14";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
