// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.DAO")]
[assembly: AssemblyDescriptionAttribute("Camada de acesso a dados da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.DAO")]
[assembly: GuidAttribute("7e4a0769-38f4-4213-b7e4-2fedd847f1e3")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.DAO";
        internal const System.String AssemblyDescription = "Camada de acesso a dados da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.DAO";
        internal const System.String Guid = "7e4a0769-38f4-4213-b7e4-2fedd847f1e3";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
