// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Business")]
[assembly: AssemblyDescriptionAttribute("Camada de regras de negócios da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Business")]
[assembly: GuidAttribute("0110581d-35a7-47f1-8e54-cee77734d2db")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Business";
        internal const System.String AssemblyDescription = "Camada de regras de negócios da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Business";
        internal const System.String Guid = "0110581d-35a7-47f1-8e54-cee77734d2db";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
