// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Common.Business")]
[assembly: AssemblyDescriptionAttribute("Camada de regras de negócios compartilhadas da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Common.Business")]
[assembly: GuidAttribute("b3b2b090-fc3b-4548-84eb-8f5298bae78a")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Common.Business";
        internal const System.String AssemblyDescription = "Camada de regras de negócios compartilhadas da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Common.Business";
        internal const System.String Guid = "b3b2b090-fc3b-4548-84eb-8f5298bae78a";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
