// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE")]
[assembly: AssemblyDescriptionAttribute("Camada do core da API do projeto EAD aluno digital.")]
[assembly: AssemblyProductAttribute("EAD.AlunoDigital")]
[assembly: GuidAttribute("f464c056-1b4a-4477-8168-9304241b9c7d")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE";
        internal const System.String AssemblyDescription = "Camada do core da API do projeto EAD aluno digital.";
        internal const System.String AssemblyProduct = "EAD.AlunoDigital";
        internal const System.String Guid = "f464c056-1b4a-4477-8168-9304241b9c7d";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
