// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Common")]
[assembly: AssemblyDescriptionAttribute("Camada do core compartilhado da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Common")]
[assembly: GuidAttribute("943f2552-6db2-40c9-a0c5-06708ea8254c")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Common";
        internal const System.String AssemblyDescription = "Camada do core compartilhado da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Common";
        internal const System.String Guid = "943f2552-6db2-40c9-a0c5-06708ea8254c";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
