// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("NAME_REPLACE.Abstraction")]
[assembly: AssemblyDescriptionAttribute("Camada de abstrações da API do projeto.")]
[assembly: AssemblyProductAttribute("NAME_REPLACE.Abstraction")]
[assembly: GuidAttribute("7f22fd06-01bd-4db8-b9ec-56584c88a02f")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2016")]
[assembly: AssemblyCompanyAttribute("NAME_REPLACE")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "NAME_REPLACE.Abstraction";
        internal const System.String AssemblyDescription = "Camada de abstrações da API do projeto.";
        internal const System.String AssemblyProduct = "NAME_REPLACE.Abstraction";
        internal const System.String Guid = "7f22fd06-01bd-4db8-b9ec-56584c88a02f";
        internal const System.String AssemblyCopyright = "Copyright ©  2016";
        internal const System.String AssemblyCompany = "NAME_REPLACE";
        internal const System.String AssemblyVersion = "0.1.0";
        internal const System.String AssemblyFileVersion = "0.1.0";
    }
}
